<a href="https://colab.research.google.com/github/julia-zhmurko/JuliaZhmurko-ML/blob/main/%D0%9B%D0%B0%D0%B1%D0%BE%D1%80%D0%B0%D1%82%D0%BE%D1%80%D0%BD%D1%96_%D1%80%D0%BE%D0%B1%D0%BE%D1%82%D0%B8/%D0%96%D0%BC%D1%83%D1%80%D0%BA%D0%BE_%D0%AE%D0%BB%D1%96%D1%8F_%D0%A4%D0%86%D0%A2_4_10_%22%D0%9B%D0%B0%D0%B1%D0%BE%D1%80%D0%B0%D1%82%D0%BE%D1%80%D0%BD%D0%B0_%D1%80%D0%BE%D0%B1%D0%BE%D1%82%D0%B0_1_Numpy_ipynb%22.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Лабораторна робота 1. NumPy

**Тема:** основи роботи з бібліотекою NumPy, масиви, вектори та матриці.

### Правила роботи
- Виконуйте завдання послідовно.
- Для обчислень використовуйте можливості **NumPy**.
- Не замінюйте операції NumPy звичайними Python-циклами, якщо це прямо не вказано в умові.
- Після виконання кожного завдання виводьте отриманий результат.


## 0. Підготовка середовища

### Завдання 0
Імпортуйте бібліотеку NumPy з псевдонімом `np`. Виведіть версію встановленої бібліотеки NumPy.

In [2]:
# Код студента
import numpy as np

print("NumPy version:", np.__version__)

NumPy version: 2.1.3


## 1. Створення масивів NumPy

### Завдання 1
Створіть одновимірний NumPy-масив із чисел:
`[2, 4, 6, 8, 10]`.

Виведіть масив та його тип за допомогою `type()`.

In [5]:
# Код студента
arr = np.array([2, 4, 6, 8, 10], dtype = np.int64)

print("Масив arr:")
print(arr)

print("Тип масиву arr:", type(arr))
print("Тип елементів масиву arr:", arr.dtype)

Масив arr:
[ 2  4  6  8 10]
Тип масиву arr: <class 'numpy.ndarray'>
Тип елементів масиву arr: int64


### Завдання 2
Створіть:
1. масив із 10 нулів;
2. масив із 8 одиниць;
3. масив із 6 елементів, усі значення яких дорівнюють `7`.

Використайте відповідні функції NumPy.

In [21]:
# Код студента
#1
zeros_arr = np.zeros(10, dtype = np.int32)
print("\nМасив із 10 нулів =\n", zeros_arr)

#2
ones_arr = np.ones(8, dtype = np.int32)
print("\nМасив із 8 одиниць =\n", ones_arr)

#3
full_arr = np.full(6, 7)
print("\nМасив із 6 семірок =\n", full_arr)


Масив із 10 нулів =
 [0 0 0 0 0 0 0 0 0 0]

Масив із 8 одиниць =
 [1 1 1 1 1 1 1 1]

Масив із 6 семірок =
 [7 7 7 7 7 7]


### Завдання 3
Створіть масив цілих чисел від `1` до `20` включно.

Після цього створіть окремий масив парних чисел від `2` до `20`.

In [17]:
# Код студента
arr = np.arange(1, 21, 1)
print("Масив arr:")
print(arr)

pair_arr = np.arange(2, 21, 2)
print("Масив парних чисел pair_arr:")
print(pair_arr)

Масив arr:
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Масив парних чисел pair_arr:
[ 2  4  6  8 10 12 14 16 18 20]


### Завдання 4
За допомогою `np.linspace()` створіть масив із **11 рівновіддалених чисел** від `0` до `1` включно.

In [18]:
# Код студента
arr = np.linspace(0, 1, num = 11)
print("Масив із 11 рівновіддалених точок arr:", arr)

Масив із 11 рівновіддалених точок arr: [0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


### Завдання 5
Створіть матрицю розміром `3 × 4`, заповнену числами від `1` до `12`.

Спочатку створіть одновимірний масив, а потім змініть його форму.

In [19]:
# Код студента
arr = np.arange(1, 13, 1)
print("Одновимірний масив arr:")
print(arr)

m = arr.reshape(3, 4)
print("\nМатриця m (змінений одновимірний масив arr):")
print(m)

Одновимірний масив arr:
[ 1  2  3  4  5  6  7  8  9 10 11 12]

Матриця m (змінений одновимірний масив arr):
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


## 2. Основні характеристики масивів

### Завдання 6
Для матриці, створеної у попередньому завданні, визначте та виведіть:
- кількість вимірів;
- форму;
- загальну кількість елементів;
- тип даних елементів.

Використайте атрибути `ndim`, `shape`, `size`, `dtype`.

In [20]:
# Код студента
arr = np.arange(1, 13, 1)
m = arr.reshape(3, 4)
print("\nМатриця m:")
print(m)

print("\nКількість вимірів ndim:", m.ndim)
print("Розмір масиву shape:", m.shape)
print("Загальна кількість елементів size:", m.size)
print("Тип даних елементів dtype:", m.dtype)


Матриця m:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Кількість вимірів ndim: 2
Розмір масиву shape: (3, 4)
Загальна кількість елементів size: 12
Тип даних елементів dtype: int64


### Завдання 7
Створіть масив:
`[1.2, 3.5, 5.7, 7.9]`.

Перетворіть його елементи на цілі числа за допомогою `astype()` та виведіть новий масив.

In [23]:
# Код студента
x = np.array([1.2, 3.5, 5.7, 7.9], dtype=np.float32)
print("Масив x:", x)
print("Тип елементів масиву x (x.dtype):", x.dtype)

y = x.astype(np.int32)
print("Масив цілих чисел y:", y)
print("Тип елементів масиву y (y.dtype):", y.dtype)


Масив x: [1.2 3.5 5.7 7.9]
Тип елементів масиву x (x.dtype): float32
Масив цілих чисел y: [1 3 5 7]
Тип елементів масиву y (y.dtype): int32


## 3. Індексація та зрізи

### Завдання 8
Створіть масив:
`[10, 20, 30, 40, 50, 60, 70, 80]`.

Виведіть:
1. перший елемент;
2. останній елемент;
3. елементи з індексами від `2` до `5` включно;
4. кожен другий елемент.

In [55]:
# Код студента
arr = np.arange(10, 81, 10)
print("Масив arr", arr)

#1
print("1-й елемент масиву arr:", arr[0])
#2
print("Останній елемент масиву arr:", arr[-1])
#3
print("Елементи масиву arr з індексами від 2 до 5 включно:", arr[2:6])
#4
print("Кожен 2-й елемент масиву arr", arr[1::2])

Масив arr [10 20 30 40 50 60 70 80]
1-й елемент масиву arr: 10
Останній елемент масиву arr: 80
Елементи масиву arr з індексами від 2 до 5 включно: [30 40 50 60]
Кожен 2-й елемент масиву arr [20 40 60 80]


### Завдання 9
Створіть матрицю:

```text
[[ 1,  2,  3,  4],
 [ 5,  6,  7,  8],
 [ 9, 10, 11, 12]]
```

Виведіть:
1. елемент `7`;
2. другий рядок;
3. третій стовпець;
4. підматрицю з останніх двох рядків і перших двох стовпців.

In [33]:
# Код студента
arr = np.arange(1, 13, 1)
m = arr.reshape(3, 4)
print("Матриця m:")
print(m)

#1
print("\nЕлемент 7 із матриці m:", m[1, 2])
#2
print("2-й рядок матриці m:", m[1, 0:])
#3
print("3-й стовпець матриці m:", m[0:, 2])
#4
print("Підматриця з останніх 2-х рядків і перших 2-х стовпців:")
print(m[-2:, :2])

Матриця m:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Елемент 7 із матриці m: 7
2-й рядок матриці m: [5 6 7 8]
3-й стовпець матриці m: [ 3  7 11]
Підматриця з останніх 2-х рядків і перших 2-х стовпців:
[[ 5  6]
 [ 9 10]]


### Завдання 10
Створіть масив чисел від `1` до `15`.

Замініть усі елементи з індексами від `5` до `9` включно на число `0`.

In [109]:
# Код студента
arr = np.arange(1, 16, 1)
print("Масив arr:", arr)

view = arr[5:10]
view[0:5] = 0
print("Масив arr із нульовими елементами в індексах 5-9:", arr)

Масив arr: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
Масив arr із нульовими елементами в індексах 5-9: [ 1  2  3  4  5  0  0  0  0  0 11 12 13 14 15]


## 4. Арифметичні операції та агрегатні функції

### Завдання 11
Створіть два масиви:

```python
a = [1, 2, 3, 4, 5]
b = [10, 20, 30, 40, 50]
```

Виконайте поелементно:
- додавання;
- віднімання;
- множення;
- ділення.

In [118]:
# Код студента
a = np.arange(1, 6, 1)
print("Масив a:", a)

b = np.arange(10, 51, 10)
print("Масив b:", b)

print("Результат додавання a + b: ", a + b)
print("Результат віднімання a - b: ", a - b)
print("Результат множення a * b: ", a * b)
print("Результат ділення a / b: ", a / b)

Масив a: [1 2 3 4 5]
Масив b: [10 20 30 40 50]
Результат додавання a + b:  [11 22 33 44 55]
Результат віднімання a - b:  [ -9 -18 -27 -36 -45]
Результат множення a * b:  [ 10  40  90 160 250]
Результат ділення a / b:  [0.1 0.1 0.1 0.1 0.1]


### Завдання 12
Для масиву:

`[4, 8, 15, 16, 23, 42]`

обчисліть:
- суму;
- середнє значення;
- мінімум;
- максимум;
- медіану;
- стандартне відхилення.

In [129]:
# Код студента
x = np.array([4, 8, 15, 16, 23, 42])

print("Сума елементів масиву x:", x.sum())
print("Середнє значення елементів масиву x:", x.mean())
print("Мінімальне значення серед елментів масиву x:", x.min())
print("Максимальне значення серед елментів масиву x:", x.max())
print("Медіана елементів масиву x:", np.median(x))
print("Стандартне відхилення елементів масиву x:", np.std(x))

Сума елементів масиву x: 108
Середнє значення елементів масиву x: 18.0
Мінімальне значення серед елментів масиву x: 4
Максимальне значення серед елментів масиву x: 42
Медіана елементів масиву x: 15.5
Стандартне відхилення елементів масиву x: 12.315302134607444


### Завдання 13
Створіть матрицю:

```text
[[1, 2, 3],
 [4, 5, 6],
 [7, 8, 9]]
```

Обчисліть:
1. суму всіх елементів;
2. суму по кожному стовпцю;
3. суму по кожному рядку;
4. середнє значення по кожному стовпцю.

In [137]:
# Код студента
arr = np.arange(1, 10, 1)
m = arr.reshape(3, 3)
print("Матриця m:")
print(m)

#1
print("\nСума всіх елементів матриці m:", m.sum())
#2
print("Сума по кожному стовпцю матриці m:", m.sum(axis = 0))
#3
print("Сума по кожному рядку матриці m:", m.sum(axis = 1))
#4
print("Середнє занчення по кожному стовпцю матриці m:", m.mean(axis = 0))

Матриця m:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Сума всіх елементів матриці m: 45
Сума по кожному стовпцю матриці m: [12 15 18]
Сума по кожному рядку матриці m: [ 6 15 24]
Середнє занчення по кожному стовпцю матриці m: [4. 5. 6.]


### Завдання 14
Для масиву чисел від `1` до `10` обчисліть:
- квадрат кожного елемента;
- квадратний корінь кожного елемента;
- натуральний логарифм кожного елемента.

Використайте функції NumPy.

In [149]:
# Код студента
arr = np.arange(1, 11, 1)
print("Масив arr:", arr)

print("\nКвадрат кожного елемента масиву arr:", np.square(arr))
print("Квадратний корінь кожного елемента масиву arr:")
print(np.sqrt(arr))
print("Натуральний логарифм кожного елемента масиву arr:")
print(np.log(arr))

Масив arr: [ 1  2  3  4  5  6  7  8  9 10]

Квадрат кожного елемента масиву arr: [  1   4   9  16  25  36  49  64  81 100]
Квадратний корінь кожного елемента масиву arr:
[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.64575131 2.82842712 3.         3.16227766]
Натуральний логарифм кожного елемента масиву arr:
[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.94591015 2.07944154 2.19722458 2.30258509]


## 5. Логічні операції та фільтрація

### Завдання 15
Створіть масив:

`[3, 7, 12, 18, 21, 25, 30, 34]`

За допомогою булевої маски виведіть:
1. усі числа, більші за `15`;
2. усі парні числа;
3. числа в діапазоні від `10` до `30` включно.

In [167]:
# Код студента
x = np.array([3, 7, 12, 18, 21, 25, 30, 34])
print("Масив x:", x)

#1
mask_1 = x > 15
print("\nБулеві значення mask_1:", mask_1)
print("Усі числа масиву x, більші за 15:", x[mask_1])

#2
mask_2 = x % 2 == 0
print("\nБулеві значення mask_2:", mask_2)
print("Усі парні числа масиву x:", x[mask_2])

#3
mask_3 = (x >= 10) & (x <= 30)
print("\nБулеві значення mask_3:", mask_3)
print("Усі числа масиву x в діапазоні 10-30:", x[mask_3])

Масив x: [ 3  7 12 18 21 25 30 34]

Булеві значення mask_1: [False False False  True  True  True  True  True]
Усі числа масиву x, більші за 15: [18 21 25 30 34]

Булеві значення mask_2: [False False  True  True False False  True  True]
Усі парні числа масиву x: [12 18 30 34]

Булеві значення mask_3: [False False  True  True  True  True  True False]
Усі числа масиву x в діапазоні 10-30: [12 18 21 25 30]


### Завдання 16
Для масиву:

`[-5, 3, -2, 8, -1, 10, 0]`

замініть усі від’ємні значення на `0`.

Не використовуйте цикл `for`.

In [176]:
# Код студента
arr = np.array([-5, 3, -2, 8, -1, 10, 0])
print("Масив arr:", arr)

mask = arr < 0
print("Булеві значення mask:", mask)

arr[mask] = 0
print("Масив arr із заміненими від'ємними числами на 0:", arr)

Масив arr: [-5  3 -2  8 -1 10  0]
Булеві значення mask: [ True False  True False  True False False]
Масив arr із заміненими від'ємними числами на 0: [ 0  3  0  8  0 10  0]


### Завдання 17
Створіть масив випадкових цілих чисел від `0` до `100` розміром `20`.

Порахуйте:
- скільки елементів більші за `50`;
- скільки елементів менші або дорівнюють `50`.

Для відтворюваності встановіть `np.random.seed(42)`.

In [192]:
# Код студента
rng = np.random.default_rng(seed = 42)
integers = rng.integers(0, 101, size = 20)
print("Масив integers:", integers)

target = 50

mask_1 = integers > target
print("\nБулеві значення mask_1:", mask_1)
result_1 = mask_1.sum()
print("Кількість елементів масиву integers, що >50:", result_1)

mask_2 = integers <= target
print("\nБулеві значення mask_2:", mask_2)
result_2 = mask_2.sum()
print("Кількість елементів масиву integers, що <=50:", result_2)

Масив integers: [ 9 78 66 44 43 86  8 70 20  9 53 98 74 76 72 79 51 12 84 45]

Булеві значення mask_1: [False  True  True False False  True False  True False False  True  True
  True  True  True  True  True False  True False]
Кількість елементів масиву integers, що >50: 12

Булеві значення mask_2: [ True False False  True  True False  True False  True  True False False
 False False False False False  True False  True]
Кількість елементів масиву integers, що <=50: 8


## 6. Зміна форми та об'єднання масивів

### Завдання 18
Створіть масив чисел від `1` до `24`.

Перетворіть його:
1. у матрицю `4 × 6`;
2. у матрицю `6 × 4`;
3. у тривимірний масив форми `2 × 3 × 4`.

Після кожного перетворення виведіть `shape`.

In [233]:
# Код студента
arr = np.arange(1, 25, 1)
print("Масив arr:", arr)
print("Форма масиву arr:", arr.shape)

#1
m_1 = arr.reshape(4, 6)
print("\nМатриця m_1:")
print("Форма матриці m_1:", m_1.shape)
print(m_1)

#2
m_2 = arr.reshape(6, 4)
print("\nМатриця m_2:")
print("Форма матриці m_2:", m_2.shape)
print(m_2)

#3
arr_1 = arr.reshape(2, 3, 4)
print("\nТривимірний масив arr_1:")
print("Форма тривимірного масиву arr_1:", arr_1.shape)
print(arr_1)

Масив arr: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
Форма масиву arr: (24,)

Матриця m_1:
Форма матриці m_1: (4, 6)
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]]

Матриця m_2:
Форма матриці m_2: (6, 4)
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]

Тривимірний масив arr_1:
Форма тривимірного масиву arr_1: (2, 3, 4)
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]


### Завдання 19
Створіть дві матриці:

```text
A = [[1, 2],
     [3, 4]]

B = [[5, 6],
     [7, 8]]
```

Об’єднайте їх:
1. вертикально;
2. горизонтально.

Використайте функції NumPy.

In [34]:
# Код студента
arr_1 = np.arange(1, 5, 1)
a = arr_1.reshape(2, 2)
print("Матриця A:")
print(a)

arr_2 = np.arange(5, 9, 1)
b = arr_2.reshape(2, 2)
print("\nМатриця B:")
print(b)

#1
print("\nВертикальне об'єднання матриць A та B (варіант 1):")
print(np.concatenate([a,b], axis = 0))
print("\nВертикальне об'єднання матриць A та B (варіант 2):")
print(np.vstack([a, b]))

#2
print("\nГоризонтальне об'єднання матриць A та B (варіант 1):")
print(np.concatenate([a,b], axis = 1))
print("\nГоризонтальне об'єднання матриць A та B (варіант 2):")
print(np.hstack([a, b]))


Матриця A:
[[1 2]
 [3 4]]

Матриця B:
[[5 6]
 [7 8]]

Вертикальне об'єднання матриць A та B (варіант 1):
[[1 2]
 [3 4]
 [5 6]
 [7 8]]

Вертикальне об'єднання матриць A та B (варіант 2):
[[1 2]
 [3 4]
 [5 6]
 [7 8]]

Горизонтальне об'єднання матриць A та B (варіант 1):
[[1 2 5 6]
 [3 4 7 8]]

Горизонтальне об'єднання матриць A та B (варіант 2):
[[1 2 5 6]
 [3 4 7 8]]


### Завдання 20
Створіть матрицю `3 × 4` із числами від `1` до `12`.

Перетворіть її назад в одновимірний масив двома способами:
- за допомогою `flatten()`;
- за допомогою `ravel()`.

Порівняйте результати.

In [253]:
# Код студента
arr = np.arange(1, 13, 1)
m = arr.reshape(3, 4)
print("Матриця m:")
print(m)

flat_arr = m.flatten()
ravel_arr = m.ravel()

print("\nОдновимірний масив (flatten):", flat_arr)
print("Одновимірний масив (ravel):", ravel_arr)

print("\nПеревірка різниці (зміна оригінальної матриці):")
m[0, 0] = 999
print("flatten[0]:", flat_arr[0])
print("ravel[0]:", ravel_arr[0])

Матриця m:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Одновимірний масив (flatten): [ 1  2  3  4  5  6  7  8  9 10 11 12]
Одновимірний масив (ravel): [ 1  2  3  4  5  6  7  8  9 10 11 12]

Перевірка різниці (зміна оригінальної матриці):
flatten[0]: 1
ravel[0]: 999


## 7. Дії з векторами

### Завдання 21
Дано два вектори:

```text
a = [2, 4, 6]
b = [1, 3, 5]
```

Знайдіть:
- суму векторів;
- різницю векторів;
- результат множення кожного вектора на число `3`.

In [266]:
# Код студента
a = np.arange(2, 7, 2)
print("Вектор а:", a)

b = np.arange(1, 6, 2)
print("Вектор b:", b)

print("Сума векторів а + b:", np.add(a,b))
print("Різниця векторів а - b:", np.subtract(a,b))
print("Результат множення вектора a на число 3:", np.multiply(a, 3))
print("Результат множення вектора b на число 3:", np.multiply(b, 3))

Вектор а: [2 4 6]
Вектор b: [1 3 5]
Сума векторів а + b: [ 3  7 11]
Різниця векторів а - b: [1 1 1]
Результат множення вектора a на число 3: [ 6 12 18]
Результат множення вектора b на число 3: [ 3  9 15]


### Завдання 22
Для векторів:

```text
a = [1, 2, 3]
b = [4, 5, 6]
```

Обчисліть їх **скалярний добуток** двома способами:
1. за допомогою `np.dot()`;
2. за допомогою оператора `@`.

In [7]:
# Код студента
a = np.arange(1, 4, 1)
print("Вектор а:", a)

b = np.arange(4, 7, 1)
print("Вектор b:", b)

#1
print("Скалярний добуток векторів а та b (np.dot):", np.dot(a,b))
#2
print("Скалярний добуток векторів а та b (@):", a @ b)

Вектор а: [1 2 3]
Вектор b: [4 5 6]
Скалярний добуток векторів а та b (np.dot): 32
Скалярний добуток векторів а та b (@): 32


### Завдання 23
Для вектора:

```text
v = [3, 4]
```

обчисліть його евклідову норму.

Потім нормалізуйте вектор, тобто отримайте вектор одиничної довжини.

In [11]:
# Код студента
v = np.array([3, 4])
print("Евклідова норма вектора v:", np.linalg.norm(v))
print("Нормалізований вектор v (вектор одиничної довжини):", v / np.linalg.norm(v) )

print("\nПеревірка: довжина нормалізованого вектора має дорівнювати 1.0")
print("Довжина нормалізованого вектора v:", np.linalg.norm(v / np.linalg.norm(v)))

Евклідова норма вектора v: 5.0
Нормалізований вектор v (вектор одиничної довжини): [0.6 0.8]

Перевірка: довжина нормалізованого вектора має дорівнювати 1.0
Довжина нормалізованого вектора v: 1.0


### Завдання 24
Дано вектори:

```text
a = [1, 0, 0]
b = [0, 1, 0]
```

Знайдіть їх векторний добуток за допомогою `np.cross()`.

In [13]:
# Код студента
a = np.array([1, 0, 0])
print("Вектор а:", a)
b = np.array([0, 1, 0])
print("Вектор b:", b)

print("Векторний добуток векторів (a x b):", np.cross(a,b))

Вектор а: [1 0 0]
Вектор b: [0 1 0]
Векторний добуток векторів (a x b): [0 0 1]


### Завдання 25
Дано два вектори:

```text
a = [1, 2]
b = [2, 1]
```

Обчисліть косинус кута між ними за формулою через скалярний добуток і норми векторів.

Додатково знайдіть сам кут у градусах.

In [4]:
# Код студента
a = np.array([1, 2])
print("Вектор а:", a)

b = np.array([2, 1])
print("Вектор b:", b)

print("\nСкалярний добуток векторів (a @ b):", a @ b)
print("Норма вектора a:", np.linalg.norm(a))
print("Норма вектора b:", np.linalg.norm(b))

cos_ang = (a @ b) / (np.linalg.norm(a) * np.linalg.norm(b))
print("\nКосинус кута між векторами а та b:", cos_ang)


print("\nКут у радіанах:", np.arccos(cos_ang))
print("Кут у градусах:", np.degrees(np.arccos(cos_ang)))

Вектор а: [1 2]
Вектор b: [2 1]

Скалярний добуток векторів (a @ b): 4
Норма вектора a: 2.23606797749979
Норма вектора b: 2.23606797749979

Косинус кута між векторами а та b: 0.7999999999999998

Кут у радіанах: 0.6435011087932847
Кут у градусах: 36.86989764584404


## 8. Дії з матрицями

### Завдання 26
Дано матрицю:

```text
A = [[1, 2, 3],
     [4, 5, 6]]
```

Знайдіть транспоновану матрицю двома способами:
1. за допомогою `.T`;
2. за допомогою `np.transpose()`.

In [36]:
# Код студента
arr = np.arange(1, 7, 1)
a = arr.reshape(2, 3)
print("Матриця A:")
print(a)

#1
print("\nТранспонована матриця A (.T):")
print(a.T)
#2
print("\nТранспонована матриця A (np.transpose)")
print(np.transpose(a))

Матриця A:
[[1 2 3]
 [4 5 6]]

Транспонована матриця A (.T):
[[1 4]
 [2 5]
 [3 6]]

Транспонована матриця A (np.transpose)
[[1 4]
 [2 5]
 [3 6]]


### Завдання 27
Дано матриці:

```text
A = [[1, 2],
     [3, 4]]

B = [[2, 0],
     [1, 2]]
```

Обчисліть:
1. поелементний добуток `A * B`;
2. матричний добуток `A @ B`.

Поясніть у коментарі до коду, чим відрізняються ці операції.

In [38]:
# Код студента
arr = np.arange(1, 5, 1)
a = arr.reshape(2, 2)
print("Матриця A:")
print(a)

b = np.array([[2, 0], [1, 2]])
print("Матриця B:")
print(b)

#1
# Поелементний добуток (A * B) - Перемножуються елементи на однакових позиціях незалежно один від одного
# [1*2  2*0]   [2  0]
# [3*1  4*2] = [3  8]
print("\nПоелементний добуток матриць (A * B):")
print(a * b)

#2
# Матричне множення (A @ B) - Перемножуються РЯДКИ першої матриці на СТОВПЧИКИ другої
# Верхній-лівий:   (1*2 + 2*1) = 4
# Верхній-правий:  (1*0 + 2*2) = 4
# Нижній-лівий:    (3*2 + 4*1) = 10
# Нижній-правий:   (3*0 + 4*2) = 8
#   [ 4  4]
# = [10  8]
print("Матричний добуток матриць (A @ B):")
print(a @ b)

Матриця A:
[[1 2]
 [3 4]]
Матриця B:
[[2 0]
 [1 2]]

Поелементний добуток матриць (A * B):
[[2 0]
 [3 8]]
Матричний добуток матриць (A @ B):
[[ 4  4]
 [10  8]]


### Завдання 28
Для матриці:

```text
A = [[4, 7],
     [2, 6]]
```

обчисліть:
- визначник;
- обернену матрицю.

Перевірте результат, помноживши початкову матрицю на обернену.

In [39]:
# Код студента
a = np.array([[4, 7], [2, 6]])
print("Матриця A:")
print(a)

print("\nВизначник матриці A:", np.linalg.det(a))
print("Обернена матриця A^(-1):")
print(np.linalg.inv(a))

print("\nПеревірка: множення початкової матриці A на оберенену A^(-1):")
print(a @ np.linalg.inv(a))

print ("\nОкруглене значення добутку початкової матриці A на оберенену A^(-1):")
print(np.round(a @ np.linalg.inv(a), 2))

Матриця A:
[[4 7]
 [2 6]]

Визначник матриці A: 10.000000000000002
Обернена матриця A^(-1):
[[ 0.6 -0.7]
 [-0.2  0.4]]

Перевірка: множення початкової матриці A на оберенену A^(-1):
[[ 1.00000000e+00 -1.11022302e-16]
 [ 1.11022302e-16  1.00000000e+00]]

Округлене значення добутку початкової матриці A на оберенену A^(-1):
[[ 1. -0.]
 [ 0.  1.]]


### Завдання 29
Розв’яжіть систему лінійних рівнянь за допомогою NumPy:

```text
2x +  y = 5
 x + 3y = 6
```

Сформуйте матрицю коефіцієнтів `A` і вектор правих частин `b`.

Використайте `np.linalg.solve()`.

In [40]:
# Код студента
a = np.array([[2, 1], [1, 3]])
print ("Матриця коефцієнтів A:")
print(a)

b = np.array([5, 6])
print("\nВектор правих частин B:", b)

print("\nРозв'язок системи лінійних рівнянь [x, y]:", np.linalg.solve(a,b))

print("Перевірка розв'язку системи лінійних рівнянь (варіант 1):", a @ np.linalg.solve(a,b))
print("Перевірка розв'язку системи лінійних рівнянь (варіант 2):", np.allclose(a @ np.linalg.solve(a,b), b))

Матриця коефцієнтів A:
[[2 1]
 [1 3]]

Вектор правих частин B: [5 6]

Розв'язок системи лінійних рівнянь [x, y]: [1.8 1.4]
Перевірка розв'язку системи лінійних рівнянь (варіант 1): [5. 6.]
Перевірка розв'язку системи лінійних рівнянь (варіант 2): True


### Завдання 30
Створіть одиничну матрицю розміром `4 × 4`.

Перевірте властивість одиничної матриці: помножте на неї довільну матрицю `4 × 4` та порівняйте результат з початковою матрицею.

In [41]:
# Код студента
i = np.eye(4)
print("Одинична матриця I:")
print(i)

rng = np.random.default_rng(seed = 42)
integers = rng.integers(0, 12, size = (4, 4))
print("\nДовільна матриця integers:")
print(integers)

print("\nРезультат множення матриць I та integers:")
print(i @ integers)

print("Перевірка, чи дорівнює результат матриці integers:", np.allclose (integers, i @ integers))

Одинична матриця I:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

Довільна матриця integers:
[[ 1  9  7  5]
 [ 5 10  1  8]
 [ 2  1  6 11]
 [ 8  9  8  9]]

Результат множення матриць I та integers:
[[ 1.  9.  7.  5.]
 [ 5. 10.  1.  8.]
 [ 2.  1.  6. 11.]
 [ 8.  9.  8.  9.]]
Перевірка, чи дорівнює результат матриці integers: True


## 9. Broadcasting (операція трансляції)

### Завдання 31
Створіть матрицю:

```text
A = [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]]
```

Додайте число `10` до кожного її елемента.

In [42]:
# Код студента
arr = np.arange(1, 10, 1)
a = arr.reshape(3, 3)
print("Матриця A:")
print(a)

print("\nДодання числа 10 до кожного елемента матриці A:")
print(np.add(a, 10))

Матриця A:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Додання числа 10 до кожного елемента матриці A:
[[11 12 13]
 [14 15 16]
 [17 18 19]]


### Завдання 32
До матриці:

```text
A = [[1, 2, 3],
     [4, 5, 6],
     [7, 8, 9]]
```

додайте вектор:

```text
v = [10, 20, 30]
```

Проаналізуйте, як NumPy застосував broadcasting.

In [51]:
# Код студента
arr = np.arange(1, 10, 1)
a = arr.reshape(3, 3)
print("Матриця A:")
print(a)
print ("Форма матриці A:", a.shape)

v = np.array([10, 20, 30])
print("\nВектор v:", v)
print("Форма вектора v:", v.shape)

print("\nРезультат додання вектора v до матриці A:")
print(a + v)

# NumPy застосував broadcasting додаючи елементи вектора v до кожного рядка матриці А
# Перший рядок: [1 + 10, 2 + 20, 3 + 30] = [11, 22, 33]
# Другий рядок: [4 + 10, 5 + 20, 6 + 30] = [14, 25, 36]
# Третій рядок: [7 + 10, 8 + 20, 9 + 30] = [17, 28, 39]

Матриця A:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Форма матриці A: (3, 3)

Вектор v: [10 20 30]
Форма вектора v: (3,)

Результат додання вектора v до матриці A:
[[11 22 33]
 [14 25 36]
 [17 28 39]]


### Завдання 33
Нормалізуйте **кожен стовпець** матриці:

```text
A = [[10, 20, 30],
     [20, 30, 40],
     [30, 40, 50]]
```

за формулою:

\[
z = \frac{x - \mu}{\sigma}
\]

де `μ` — середнє значення стовпця, `σ` — стандартне відхилення стовпця.

Не використовуйте цикл `for`.

In [33]:
# Код студента
arr = np.array([10, 20, 30, 20, 30, 40, 30, 40, 50])
a = arr.reshape(3, 3)
print("Матриця A:")
print(a)

mu = a.mean(axis = 0)
print("\nСереднє значення за стовпцями матриці А:", mu)

sigma = a.std(axis = 0)
print("Стандартне відхилення за стовпцями матриці А:", sigma)

z = (a - mu) / sigma
print("\nНормалізована матриця A_std:")
print(z)

print("\nПеревірка: Середнє значення за стовпцями нормалізованої матриці A_std:", z.mean(axis = 0))
print("Перевірка: Стандартне відхилення за стовпцями нормалізованої матриці A_std:", z.std(axis = 0))

Матриця A:
[[10 20 30]
 [20 30 40]
 [30 40 50]]

Середнє значення за стовпцями матриці А: [20. 30. 40.]
Стандартне відхилення за стовпцями матриці А: [8.16496581 8.16496581 8.16496581]

Нормалізована матриця A_std:
[[-1.22474487 -1.22474487 -1.22474487]
 [ 0.          0.          0.        ]
 [ 1.22474487  1.22474487  1.22474487]]

Перевірка: Середнє значення за стовпцями нормалізованої матриці A_std: [0. 0. 0.]
Перевірка: Стандартне відхилення за стовпцями нормалізованої матриці A_std: [1. 1. 1.]


## 10. Випадкові дані

### Завдання 34
Встановіть `np.random.seed(42)` та створіть:
1. 10 випадкових цілих чисел від `1` до `100`;
2. матрицю `3 × 3` випадкових чисел від `0` до `1`;
3. 1000 значень із нормального розподілу.

Для третього масиву обчисліть середнє та стандартне відхилення.

In [55]:
# Код студента
rng = np.random.default_rng(seed = 42)

#1
integers = rng.integers(1, 101, size = 10)
print("Масив integers 10 випадкових цілих чисел від 1 до 100:", integers)

#2
m = rng.random((3, 3))
print("\nМатриця M випадкових чисел від 0 до 1:")
print(m)

#3
normal = rng.normal(loc = 0.0, scale = 1.0, size = 1000)
print("\nМасив normal 1000 значень із нормального розподілу:")
print(normal)

print("\nСереднє значення масиву normal:", normal.mean())
print("Стандартне відхилення масиву normal:", normal.std())

Масив integers 10 випадкових цілих чисел від 1 до 100: [ 9 78 66 44 44 86  9 70 21 10]

Матриця M випадкових чисел від 0 до 1:
[[0.97562235 0.7611397  0.78606431]
 [0.12811363 0.45038594 0.37079802]
 [0.92676499 0.64386512 0.82276161]]

Масив normal 1000 значень із нормального розподілу:
[ 4.67509342e-01 -8.59292463e-01  3.68750784e-01 -9.58882601e-01
  8.78450301e-01 -4.99259110e-02 -1.84862364e-01 -6.80929544e-01
  1.22254134e+00 -1.54529482e-01 -4.28327822e-01 -3.52133550e-01
  5.32309186e-01  3.65444064e-01  4.12732612e-01  4.30821003e-01
  2.14164760e+00 -4.06415016e-01 -5.12242729e-01 -8.13772728e-01
  6.15979423e-01  1.12897229e+00 -1.13947458e-01 -8.40156477e-01
 -8.24481216e-01  6.50592788e-01  7.43254171e-01  5.43154268e-01
 -6.65509707e-01  2.32161323e-01  1.16685809e-01  2.18688597e-01
  8.71428778e-01  2.23595549e-01  6.78913563e-01  6.75790695e-02
  2.89119399e-01  6.31288226e-01 -1.45715582e+00 -3.19671216e-01
 -4.70372654e-01 -6.38877848e-01 -2.75142251e-01  1.49494131e

### Завдання 35
Змоделюйте оцінки 30 студентів — випадкові цілі числа від `0` до `100`.

Визначте:
- середню оцінку;
- медіану;
- найвищу та найнижчу оцінки;
- кількість студентів, які отримали не менше `60`;
- відсоток студентів, які отримали не менше `90`.

In [21]:
# Код студента
rng = np.random.default_rng(seed = 42)
marks =  rng.integers(0, 101, size = 30)
print("Масив оцінок 30 студентів marks:")
print(marks)

print("\nСередня оцінка студентів:", marks.mean())
print("Медіана масиву оцінок студентів:", np.median(marks))
print("Найвища оцінка студентів:", marks.max())
print("Найнижча оцінка студентів:", marks.min())

mask_1 = marks >= 60
print("\nБулеве значення mask_1:")
print(mask_1)
result_1 = mask_1.sum()
print("Кількість студентів з оцінкою >= 60:", result_1)

mask_2 = marks >= 90
print("\nБулеве значення mask_2:")
print(mask_2)
result_2 = mask_2.mean() * 100
print("Відсоток студентів з оцінкою >= 90:", result_2)

Масив оцінок 30 студентів marks:
[ 9 78 66 44 43 86  8 70 20  9 53 98 74 76 72 79 51 12 84 45 50 37 18 93
 78 65 40 83 55 44]

Середня оцінка студентів: 54.666666666666664
Медіана масиву оцінок студентів: 54.0
Найвища оцінка студентів: 98
Найнижча оцінка студентів: 8

Булеве значення mask_1:
[False  True  True False False  True False  True False False False  True
  True  True  True  True False False  True False False False False  True
  True  True False  True False False]
Кількість студентів з оцінкою >= 60: 14

Булеве значення mask_2:
[False False False False False False False False False False False  True
 False False False False False False False False False False False  True
 False False False False False False]
Відсоток студентів з оцінкою >= 90: 6.666666666666667


## 11. Підсумкові завдання

### Завдання 36
Дано результати продажів трьох товарів за чотири місяці:

```text
sales = [[120, 150, 170, 160],
         [80,  90,  100, 110],
         [200, 180, 210, 230]]
```

Рядки — товари, стовпці — місяці.

Визначте:
1. загальний обсяг продажів кожного товару;
2. загальний обсяг продажів у кожному місяці;
3. товар із найбільшими сумарними продажами;
4. місяць із найбільшим загальним обсягом продажів;
5. середній обсяг продажів кожного товару.

In [35]:
# Код студента
sales = np.array([[120, 150, 170, 160],
                  [80,  90,  100, 110],
                  [200, 180, 210, 230]])
print("Матриця продажів 3-х товарів за 4 місяці sales:")
print(sales)

#1
total_per_product = sales.sum(axis = 1)
print("\nЗагальний обсяг продажів кожного товару:", total_per_product)

#2
total_per_month = sales.sum(axis = 0)
print("Загальний обсяг продажів у кожному місяці:", total_per_month)

#3
best_prod_idx = np.argsort(total_per_product) [-1]
best_product = best_prod_idx + 1
print("Товар із найбільшими сумарними продажами:", best_product)

#4
best_month_idx = np.argsort(total_per_month) [-1]
best_month = best_month_idx + 1
print("Місяць із найбільшим загальним обсягом продажів:", best_month)

#5
print("Середній обсяг продажів кожного товару:", sales.mean(axis = 1))

Матриця продажів 3-х товарів за 4 місяці sales:
[[120 150 170 160]
 [ 80  90 100 110]
 [200 180 210 230]]

Загальний обсяг продажів кожного товару: [600 380 820]
Загальний обсяг продажів у кожному місяці: [400 420 480 500]
Товар із найбільшими сумарними продажами: 3
Місяць із найбільшим загальним обсягом продажів: 4
Середній обсяг продажів кожного товару: [150.  95. 205.]


### Завдання 37
Створіть квадратну матрицю `5 × 5` із випадкових цілих чисел від `1` до `20`.

Виконайте:
1. знайдіть суму головної діагоналі;
2. знайдіть суму побічної діагоналі;
3. знайдіть максимальний елемент кожного рядка;
4. знайдіть мінімальний елемент кожного стовпця;
5. замініть усі елементи, менші за середнє значення всієї матриці, на `0`.

In [13]:
# Код студента
rng = np.random.default_rng(seed = 42)
m = rng.integers(1, 21, size = (5, 5))
print("Матриця M:")
print(m)

#1
print("\nСума головної діагоналі матриці M:", np.diag(m).sum())

#2
print("Сума побічної діагоналі матриці M:", np.diag(np.fliplr(m)).sum())

#3
print("Максимальний елемент кожного рядка матриці М:", m.max(axis = 1))

#4
print("Мінімальний елемент кожного стовпця матриці М:", m.min(axis = 0))

#5
print("\nСереднє значення всієї матриці М:", m.mean())
mask = m < m.mean()
print("Булеві значення mask:")
print(mask)

m[mask] = 0
print("\nЗамінені елементи матриці М, які менші за середнє значення всієї матриці:")
print(m)

Матриця M:
[[ 2 16 14  9  9]
 [18  2 14  5  2]
 [11 20 15 16 15]
 [16 11  3 17 10]
 [11  8  4 19 16]]

Сума головної діагоналі матриці M: 52
Сума побічної діагоналі матриці M: 51
Максимальний елемент кожного рядка матриці М: [16 18 20 17 19]
Мінімальний елемент кожного стовпця матриці М: [2 2 3 5 2]

Середнє значення всієї матриці М: 11.32
Булеві значення mask:
[[ True False False  True  True]
 [False  True False  True  True]
 [ True False False False False]
 [False  True  True False  True]
 [ True  True  True False False]]

Замінені елементи матриці М, які менші за середнє значення всієї матриці:
[[ 0 16 14  0  0]
 [18  0 14  0  0]
 [ 0 20 15 16 15]
 [16  0  0 17  0]
 [ 0  0  0 19 16]]


### Завдання 38
Дано матрицю ознак трьох об’єктів:

```text
X = [[2, 4, 6],
     [1, 3, 5],
     [5, 7, 9]]
```

Обчисліть **евклідову відстань** між:
- першим і другим рядком;
- першим і третім рядком;
- другим і третім рядком.

Використайте операції NumPy та `np.linalg.norm()`.

In [21]:
# Код студента
x = np.array([[2, 4, 6],
              [1, 3, 5],
              [5, 7, 9]])
print("Матриця X:")
print(x)

print("\nЕвклідова відстань між 1-м та 2-м рядком матриці Х:", np.linalg.norm(x[0] - x[1]))
print("Евклідова відстань між 1-м та 3-м рядком матриці Х:", np.linalg.norm(x[0] - x[2]))
print("Евклідова відстань між 2-м та 3-м рядком матриці Х:", np.linalg.norm(x[1] - x[2]))

Матриця X:
[[2 4 6]
 [1 3 5]
 [5 7 9]]

Евклідова відстань між 1-м та 2-м рядком матриці Х: 1.7320508075688772
Евклідова відстань між 1-м та 3-м рядком матриці Х: 5.196152422706632
Евклідова відстань між 2-м та 3-м рядком матриці Х: 6.928203230275509


### Завдання 39
Створіть матрицю `4 × 4` із довільних цілих чисел.

Для кожного рядка знайдіть його норму та створіть нову матрицю, у якій кожен рядок нормалізований до одиничної довжини.

Спробуйте виконати завдання без циклів.

In [54]:
# Код студента
rng = np.random.default_rng(seed = 42)
m = rng.integers(0, 20, size = (4, 4))
print("Матриця M:")
print(m)
print("\nФорма матриці M:", m.shape)

norm_1 = np.linalg.norm(m, axis = 1)
print("\nНорма кожного рядка матриці M:", norm_1)
print("\nФорма одновимірного масиву норм norm_1:", norm_1.shape)

norm_m = m / norm_1 [:, np.newaxis]
print("\nФорма двовимірного масиву норм norm_2:", norm_1 [:, np.newaxis].shape)
print("\nМатриця M_new із кожним рядком нормалізованим до одиничної довжини:")
print(norm_m)

check = np.linalg.norm(norm_m, axis = 1)
print("\nПеревірка: норма кожного рядка нової матриці має дорівнювати 1.0:", check)

Матриця M:
[[ 1 15 13  8]
 [ 8 17  1 13]
 [ 4  1 10 19]
 [14 15 14 15]]

Форма матриці M: (4, 4)

Норма кожного рядка матриці M: [21.42428529 22.86919325 21.86321111 29.01723626]

Форма одновимірного масиву норм norm_1: (4,)

Форма двовимірного масиву норм norm_2: (4, 1)

Матриця M_new із кожним рядком нормалізованим до одиничної довжини:
[[0.046676   0.70014004 0.60678804 0.37340802]
 [0.34981558 0.7433581  0.04372695 0.56845031]
 [0.18295574 0.04573894 0.45738935 0.86903977]
 [0.48247186 0.51693414 0.48247186 0.51693414]]

Перевірка: норма кожного рядка нової матриці має дорівнювати 1.0: [1. 1. 1. 1.]


### Завдання 40
Створіть матрицю коефіцієнтів і вектор правих частин для системи:

```text
 x + 2y +  z =  9
2x +  y -  z =  8
3x -  y + 2z =  3
```

1. Розв’яжіть систему за допомогою `np.linalg.solve()`.
2. Перевірте знайдений розв’язок матричним множенням `A @ x`.
3. Порівняйте результат із вектором `b`.

In [60]:
# Код студента
a = np.array([[1,  2,  1],
              [2,  1, -1],
              [3, -1,  2]])
print("\nМатриця коефіцієетів А:")
print(a)

b = np.array([9, 8, 3])
print("\nВектор правих частин b:", b)

#1
x = np.linalg.solve(a, b)
print("\nРозв'язок системи лінійних рівнянь:", x)

#2
print("Перевірка знайденого розв'язку:", a @ x)

#3
print("Порівняння результату із вектором b:", np.allclose(a @ x, b))


Матриця коефіцієетів А:
[[ 1  2  1]
 [ 2  1 -1]
 [ 3 -1  2]]

Вектор правих частин b: [9 8 3]

Розв'язок системи лінійних рівнянь: [ 2.22222222  3.44444444 -0.11111111]
Перевірка знайденого розв'язку: [9. 8. 3.]
Порівняння результату із вектором b: True


---

## Самоперевірка

Після виконання роботи студент повинен уміти:
- створювати та перетворювати NumPy-масиви;
- використовувати індексацію та зрізи;
- виконувати векторизовані арифметичні операції;
- застосовувати агрегатні функції;
- використовувати булеві маски;
- змінювати форму та об'єднувати масиви;
- виконувати основні дії з векторами;
- виконувати основні операції з матрицями;
- застосовувати broadcasting;
- використовувати функції `numpy.linalg` для задач лінійної алгебри.
